name: Auto Commits
on:
  workflow_dispatch:
jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Make commits
        run: |
          git config user.email "ks8164890@users.noreply.github.com"
          git config user.name "ks8164890"
          for i in $(seq 1 100); do
            echo "update $i" >> log.md
            git add .
            git commit -m "update $i"
          done
          git push
